#!/bin/bash

dmenu="rofi -dmenu"

copy() {
  keepass-dmenu.py info "$selection" "$@" | xclip -selection c
}

autotype() {
  echo "auto type $selection"

  user=$(keepass-dmenu.py info "$selection" user)
  pass=$(keepass-dmenu.py info "$selection" pass)

  xdotool type "$user"
  xdotool key Tab
  xdotool type "$pass"
  xdotool key Return
}

entries=$(keepass-dmenu.py list)
if [[ $? != 0 ]]; then
  (echo Exit; echo -n "$entries") | $dmenu -p "Error" > /dev/null
  exit 1
fi

selection=$(echo -n "$entries" | $dmenu -i -p "Search")

if [[ ${selection} == "" ]]; then
  exit 1
fi

options=$(cat << END
Copy Username
Copy Password
Copy OTP Code
$(echo -n -e "$(keepass-dmenu.py info "$selection" custom)" | while read line; do echo "Copy ${line}"; done)
Perform Auto-Type
END
)

action=$(echo -e "$options" | $dmenu -i -p "$selection")

if [[ ${action} == "Copy Username" ]]; then
  copy user
elif [[ ${action} == "Copy Password" ]]; then
  copy pass
elif [[ ${action} == "Copy OTP Code" ]]; then
  copy otp
elif [[ ${action} == "Perform Auto-Type" ]]; then
  autotype
elif [[ ${action} == "Copy "* ]]; then
  copy custom "${action/#Copy /}"
elif [[ ${action} == "" ]]; then
  exit
fi
